services:
  # PostgreSQL Database (Managed by Render)
  - type: pserv
    name: schema-sync-postgres
    plan: free
    region: oregon

  # Milvus Lite Service (Docker)
  - type: web
    name: milvus-service
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile.milvus
    healthCheckPath: /healthz
    envVars:
      - key: ETCD_USE_EMBED
        value: "true"
      - key: COMMON_STORAGETYPE
        value: "local"

  # FastAPI Application
  - type: web
    name: schema-sync-api
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      # Python version
      - key: PYTHON_VERSION
        value: "3.12.0"
      
      # PostgreSQL configuration - Auto-populated from database
      - key: METADATA_DB_HOST
        fromDatabase:
          name: schema-sync-postgres
          property: host
      
      - key: METADATA_DB_PORT
        fromDatabase:
          name: schema-sync-postgres
          property: port
      
      - key: METADATA_DB_NAME
        fromDatabase:
          name: schema-sync-postgres
          property: database
      
      - key: METADATA_DB_USER
        fromDatabase:
          name: schema-sync-postgres
          property: user
      
      - key: METADATA_DB_PASSWORD
        fromDatabase:
          name: schema-sync-postgres
          property: password
      
      # Milvus configuration - Connect to Milvus service on Render
      - key: MILVUS_HOST
        fromService:
          type: web
          name: milvus-service
          property: host
      
      - key: MILVUS_PORT
        value: "19530"

  # Attu GUI for Milvus (Optional)
  - type: web
    name: attu-gui
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile.attu
    envVars:
      - key: MILVUS_URL
        fromService:
          type: web
          name: milvus-service
          property: hostport
